/**
 * BackendAgentMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Agent call result
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(BackendAgentMessageBinary), typeDiscriminator: "binary")]
[JsonDerivedType(typeof(BackendAgentMessageChoice), typeDiscriminator: "choice")]
[JsonDerivedType(typeof(BackendAgentMessageObject), typeDiscriminator: "object")]
[JsonDerivedType(typeof(BackendAgentMessageText), typeDiscriminator: "text")]
[JsonDerivedType(typeof(BackendAgentMessageToolCall), typeDiscriminator: "tool_call")]
public abstract class BackendAgentMessage
{
    [JsonPropertyName("metadata")]
    public System.Collections.Generic.Dictionary<string, object>? Metadata { get; set; }

}

