/**
 * BackendAppUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload for updating an existing consumer application
/// </summary>
public class BackendAppUpdate : BackendApp
{
}

