/**
 * BackendAgentTools automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Represents a collection of available tools
/// </summary>
public class BackendAgentTools
{
    [JsonPropertyName("kind")]
    public string? Kind { get; set; }

    [JsonPropertyName("tools")]
    public System.Collections.Generic.List<BackendAgentTool>? Tools { get; set; }

}

