/**
 * BackendIdentityIndexEntry automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendIdentityIndexEntry
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("class")]
    public string? Class { get; set; }
}
