/**
 * BackendSdkResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Container listing target SDK languages or formats available for generator execution
/// </summary>
public class BackendSdkResponse
{
    [JsonPropertyName("kind")]
    public string? Kind { get; set; }

    [JsonPropertyName("types")]
    public BackendSdkTypes? Types { get; set; }

}

