/**
 * BackendSdkGenerate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload defining target format and configuration for triggering an SDK generation run
/// </summary>
public class BackendSdkGenerate
{
    [JsonPropertyName("format")]
    public string? Format { get; set; }

    [JsonPropertyName("config")]
    public string? Config { get; set; }

}

