/**
 * BackendAgentContentText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Text agent message
/// </summary>
public class BackendAgentContentText : BackendAgentContent
{
    [JsonPropertyName("content")]
    public string? Content { get; set; }

}

