/**
 * BackendDatabaseTables automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendDatabaseTables
{
    [JsonPropertyName("tables")]
    public List<string>? Tables { get; set; }
}
