/**
 * BackendDatabaseTableColumn automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents a column at a relation table
/// </summary>
public class BackendDatabaseTableColumn
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("length")]
    public int? Length { get; set; }

    [JsonPropertyName("precision")]
    public int? Precision { get; set; }

    [JsonPropertyName("scale")]
    public int? Scale { get; set; }

    [JsonPropertyName("unsigned")]
    public bool? Unsigned { get; set; }

    [JsonPropertyName("fixed")]
    public bool? Fixed { get; set; }

    [JsonPropertyName("notNull")]
    public bool? NotNull { get; set; }

    [JsonPropertyName("autoIncrement")]
    public bool? AutoIncrement { get; set; }

    [JsonPropertyName("default")]
    public object? Default { get; set; }

    [JsonPropertyName("comment")]
    public string? Comment { get; set; }

}

