/**
 * BackendBundleConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Fusio.SDK;

/// <summary>
/// Configuration settings and resource specs exported within the bundle
/// </summary>
public class BackendBundleConfig : Dictionary<string, object>
{
}

