/**
 * BackendPlanCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// A paginated collection of plan objects
/// </summary>
public class BackendPlanCollection : CommonCollection<BackendPlan>
{
}

