/**
 * BackendSpecificationPublish automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload defining configuration parameters for publishing an API specification export
/// </summary>
public class BackendSpecificationPublish
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("filterName")]
    public string? FilterName { get; set; }

    [JsonPropertyName("standalone")]
    public bool? Standalone { get; set; }

}

