/**
 * BackendAgentContentToolCall automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Tool call agent message
/// </summary>
public class BackendAgentContentToolCall : BackendAgentContent
{
    [JsonPropertyName("functions")]
    public System.Collections.Generic.List<BackendAgentContentToolCallFunction>? Functions { get; set; }

}

