/**
 * BackendConfigUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload for updating a system configuration entry
/// </summary>
public class BackendConfigUpdate : BackendConfig
{
}

