/**
 * BackendBundle automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents a bundle which contains action, schema, event, cronjob and trigger configurations from you local instance
/// </summary>
public class BackendBundle
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("config")]
    public BackendBundleConfig? Config { get; set; }

}

