/**
 * BackendStatisticCount automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class BackendStatisticCount
{
    [JsonPropertyName("count")]
    public int? Count { get; set; }

    [JsonPropertyName("from")]
    public System.DateTime? From { get; set; }

    [JsonPropertyName("to")]
    public System.DateTime? To { get; set; }

}

