/**
 * BackendAgentRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents an agent request
/// </summary>
public class BackendAgentRequest
{
    [JsonPropertyName("intent")]
    public string? Intent { get; set; }

    [JsonPropertyName("input")]
    public BackendAgentMessage? Input { get; set; }

}

