/**
 * BackendTaxonomy automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents a taxonomy. A taxonomy helps to internally organize operations, actions and other entities
/// </summary>
public class BackendTaxonomy
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }

    [JsonPropertyName("parentId")]
    public int? ParentId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

