/**
 * BackendDatabaseTableIndex automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class BackendDatabaseTableIndex
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("unique")]
    public bool? Unique { get; set; }

    [JsonPropertyName("columns")]
    public System.Collections.Generic.List<string>? Columns { get; set; }

}

