/**
 * BackendAgentContentBinary automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Binary agent message
/// </summary>
public class BackendAgentContentBinary : BackendAgentContent
{
    [JsonPropertyName("mime")]
    public string? Mime { get; set; }

    [JsonPropertyName("data")]
    public string? Data { get; set; }

}

