/**
 * BackendSdkGenerate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendSdkGenerate
{
    [JsonPropertyName("format")]
    public string Format { get; set; }
    [JsonPropertyName("config")]
    public string Config { get; set; }
}
