/**
 * BackendGeneratorProviderChangelog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Represents a preview changelog of entities created or updated by a generator run
/// </summary>
public class BackendGeneratorProviderChangelog
{
    [JsonPropertyName("schemas")]
    public System.Collections.Generic.List<BackendSchema>? Schemas { get; set; }

    [JsonPropertyName("actions")]
    public System.Collections.Generic.List<BackendAction>? Actions { get; set; }

    [JsonPropertyName("operations")]
    public System.Collections.Generic.List<BackendOperation>? Operations { get; set; }

}

