/**
 * BackendFileCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// A paginated collection of file objects
/// </summary>
public class BackendFileCollection : CommonCollection<BackendFile>
{
}

