/**
 * BackendIdentityConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Fusio.SDK;

/// <summary>
/// Identity provider configuration containing key-value parameters
/// </summary>
public class BackendIdentityConfig : Dictionary<string, object>
{
}

