/**
 * BackendAuditObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Fusio.SDK;

/// <summary>
/// A key value object containing the changes
/// </summary>
public class BackendAuditObject : Dictionary<string, object>
{
}

