/**
 * BackendRateCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload for creating a new rate limit policy
/// </summary>
public class BackendRateCreate : BackendRate
{
}

