/**
 * BackendTrashData automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents a deleted item stored in the trash bin
/// </summary>
public class BackendTrashData
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }

    [JsonPropertyName("status")]
    public int? Status { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

