/**
 * BackendDatabaseRow automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Fusio.SDK;

/// <summary>
/// This object represents a row on a relational table
/// </summary>
public class BackendDatabaseRow : Dictionary<string, object>
{
}

