/**
 * BackendAgentContentChoice automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Choice agent message
/// </summary>
public class BackendAgentContentChoice : BackendAgentContent
{
    [JsonPropertyName("items")]
    public System.Collections.Generic.List<BackendAgentContent>? Items { get; set; }

}

