/**
 * BackendTestConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Configuration parameters for executing a test run
/// </summary>
public class BackendTestConfig : BackendActionExecuteRequest
{
}

