/**
 * BackendSchemaPreviewResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Response container for a generated schema code preview
/// </summary>
public class BackendSchemaPreviewResponse
{
    [JsonPropertyName("preview")]
    public string? Preview { get; set; }

}

