/**
 * BackendAgentMessageTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace Fusio.SDK;

public class BackendAgentMessageTag : TagAbstract {
    public BackendAgentMessageTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    /**
     * Returns a paginated list of agent messages
     */
    public async Task<BackendAgentMessageCollection> GetAll(string agentId, string chatId)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("agent_id", agentId);

        Dictionary<string, object> queryParams = new();
        queryParams.Add("chat_id", chatId);

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/backend/agent/$agent_id<[0-9]+|^~>/message", pathParams), Method.Get);
        this.Parser.Query(request, queryParams, queryStructNames);


        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            var data = this.Parser.Parse<BackendAgentMessageCollection>(response.Content);

            return data;
        }

        var statusCode = (int) response.StatusCode;
        if (statusCode >= 0 && statusCode <= 999)
        {
            var data = this.Parser.Parse<CommonMessage>(response.Content);

            throw new CommonMessageException(data);
        }

        throw new UnknownStatusCodeException("The server returned an unknown status code: " + statusCode);
    }
    /**
     * Submits a new agent message
     */
    public async Task<CommonAgentOutput> Submit(string agentId, CommonAgentInput payload)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("agent_id", agentId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/backend/agent/$agent_id<[0-9]+|^~>/message", pathParams), Method.Post);
        this.Parser.Query(request, queryParams, queryStructNames);
        request.AddJsonBody(JsonSerializer.Serialize(payload));

        request.AddOrUpdateHeader("Content-Type", "application/json");

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            var data = this.Parser.Parse<CommonAgentOutput>(response.Content);

            return data;
        }

        var statusCode = (int) response.StatusCode;
        if (statusCode >= 0 && statusCode <= 999)
        {
            var data = this.Parser.Parse<CommonMessage>(response.Content);

            throw new CommonMessageException(data);
        }

        throw new UnknownStatusCodeException("The server returned an unknown status code: " + statusCode);
    }


}
