/**
 * BackendScopeCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// A paginated collection of scope objects
/// </summary>
public class BackendScopeCollection : CommonCollection<BackendScope>
{
}

