/**
 * BackendBundleUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload for updating an existing configuration bundle
/// </summary>
public class BackendBundleUpdate : BackendBundle
{
}

