/**
 * BackendTaxonomyCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload for creating a new taxonomy organization node
/// </summary>
public class BackendTaxonomyCreate : BackendTaxonomy
{
}

