/**
 * BackendCronjobError automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendCronjobError
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }
    [JsonPropertyName("trace")]
    public string? Trace { get; set; }
    [JsonPropertyName("file")]
    public string? File { get; set; }
    [JsonPropertyName("line")]
    public int? Line { get; set; }
}
