/**
 * BackendConnection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendConnection
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("class")]
    public string? Class { get; set; }
    [JsonPropertyName("oauth2")]
    public bool? Oauth { get; set; }
    [JsonPropertyName("config")]
    public BackendConnectionConfig? Config { get; set; }
    [JsonPropertyName("metadata")]
    public CommonMetadata? Metadata { get; set; }
}
