/**
 * BackendSpecificationChangelog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class BackendSpecificationChangelog
{
    [JsonPropertyName("master")]
    public object? Master { get; set; }

    [JsonPropertyName("tag")]
    public object? Tag { get; set; }

    [JsonPropertyName("version")]
    public string? Version { get; set; }

    [JsonPropertyName("changelog")]
    public string? Changelog { get; set; }

}

