/**
 * BackendWebhookCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Request payload to create a new webhook subscription
/// </summary>
public class BackendWebhookCreate : BackendWebhook
{
}

