/**
 * BackendAgentContentObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Structured agent message
/// </summary>
public class BackendAgentContentObject : BackendAgentContent
{
    [JsonPropertyName("payload")]
    public object? Payload { get; set; }

}

