/**
 * BackendStatisticChart automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendStatisticChart
{
    [JsonPropertyName("labels")]
    public List<string> Labels { get; set; }
    [JsonPropertyName("data")]
    public List<BackendStatisticChartData> Data { get; set; }
    [JsonPropertyName("series")]
    public List<string> Series { get; set; }
}
