/**
 * BackendTrashTypes automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendTrashTypes
{
    [JsonPropertyName("types")]
    public List<string>? Types { get; set; }
}
