/**
 * BackendGeneratorProvider automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class BackendGeneratorProvider
{
    [JsonPropertyName("path")]
    public string? Path { get; set; }
    [JsonPropertyName("scopes")]
    public List<string>? Scopes { get; set; }
    [JsonPropertyName("public")]
    public bool? Public { get; set; }
    [JsonPropertyName("config")]
    public BackendGeneratorProviderConfig? Config { get; set; }
}
