/**
 * CommonAgentOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents an agent output
/// </summary>
public class CommonAgentOutput
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("output")]
    public CommonAgentContent? Output { get; set; }

}

