/**
 * CommonFormElementTextArea automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class CommonFormElementTextArea : CommonFormElement
{
    [JsonPropertyName("mode")]
    public string? Mode { get; set; }
}
