/**
 * CommonFormElementAgent automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Form element which represents an agent selection
/// </summary>
public class CommonFormElementAgent : CommonFormElementSelect
{
}

