/**
 * CommonFormElementSelect automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Form element which represents a select element
/// </summary>
public class CommonFormElementSelect : CommonFormElement
{
    [JsonPropertyName("options")]
    public System.Collections.Generic.List<CommonFormElementSelectOption>? Options { get; set; }

}

