/**
 * CommonCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class CommonCollection<T>
{
    [JsonPropertyName("totalResults")]
    public int? TotalResults { get; set; }
    [JsonPropertyName("startIndex")]
    public int? StartIndex { get; set; }
    [JsonPropertyName("itemsPerPage")]
    public int? ItemsPerPage { get; set; }
    [JsonPropertyName("entry")]
    public List<T>? Entry { get; set; }
}
