/**
 * CommonFormContainer automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class CommonFormContainer
{
    [JsonPropertyName("element")]
    public List<object> Element { get; set; }
}
