/**
 * CommonAgentInput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// This object represents an agent input
/// </summary>
public class CommonAgentInput
{
    [JsonPropertyName("previousId")]
    public string? PreviousId { get; set; }

    [JsonPropertyName("input")]
    public CommonAgentContent? Input { get; set; }

}

