/**
 * CommonAgentContent automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Agent message
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(CommonAgentContentBinary), typeDiscriminator: "binary")]
[JsonDerivedType(typeof(CommonAgentContentChoice), typeDiscriminator: "choice")]
[JsonDerivedType(typeof(CommonAgentContentObject), typeDiscriminator: "object")]
[JsonDerivedType(typeof(CommonAgentContentText), typeDiscriminator: "text")]
[JsonDerivedType(typeof(CommonAgentContentToolCall), typeDiscriminator: "tool_call")]
public abstract class CommonAgentContent
{
    [JsonPropertyName("metadata")]
    public System.Collections.Generic.Dictionary<string, object>? Metadata { get; set; }

}

