/**
 * ConsumerUserRefresh automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class ConsumerUserRefresh
{
    [JsonPropertyName("refresh_token")]
    public string RefreshToken { get; set; }
}
