/**
 * ConsumerScopeCategories automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class ConsumerScopeCategories
{
    [JsonPropertyName("categories")]
    public System.Collections.Generic.List<ConsumerScopeCategory>? Categories { get; set; }

}

