/**
 * ConsumerEventCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Collection of event definitions
/// </summary>
public class ConsumerEventCollection : CommonCollection<ConsumerEvent>
{
}

