/**
 * ConsumerUserActivate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

/// <summary>
/// Payload used to activate a user account via token
/// </summary>
public class ConsumerUserActivate
{
    [JsonPropertyName("token")]
    public string? Token { get; set; }

}

