/**
 * ConsumerScopeCategory automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class ConsumerScopeCategory
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("scopes")]
    public System.Collections.Generic.List<ConsumerScopeCategoryScope>? Scopes { get; set; }

}

