/**
 * MarketplaceBundleSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class MarketplaceBundleSchema
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("source")]
    public MarketplaceBundleSchemaSource? Source { get; set; }

}

