/**
 * MarketplaceObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace Fusio.SDK;
public class MarketplaceObject
{
    [JsonPropertyName("id")]
    public int? Id { get; set; }
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("author")]
    public MarketplaceUser? Author { get; set; }
    [JsonPropertyName("version")]
    public string? Version { get; set; }
    [JsonPropertyName("icon")]
    public string? Icon { get; set; }
    [JsonPropertyName("summary")]
    public string? Summary { get; set; }
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    [JsonPropertyName("cost")]
    public int? Cost { get; set; }
    [JsonPropertyName("updateDate")]
    public DateTime? UpdateDate { get; set; }
    [JsonPropertyName("insertDate")]
    public DateTime? InsertDate { get; set; }
}
