/**
 * MarketplaceBundleTrigger automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class MarketplaceBundleTrigger
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("event")]
    public string? Event { get; set; }

    [JsonPropertyName("action")]
    public string? Action { get; set; }

}

