/**
 * SystemSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class SystemSchema
{
    [JsonPropertyName("kind")]
    public string? Kind { get; set; }

    [JsonPropertyName("schema")]
    public SystemSchemaTypeSchema? Schema { get; set; }

    [JsonPropertyName("form")]
    public SystemSchemaForm? Form { get; set; }

}

