/**
 * SystemRoute automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class SystemRoute
{
    [JsonPropertyName("kind")]
    public string? Kind { get; set; }

    [JsonPropertyName("routes")]
    public SystemRoutePath? Routes { get; set; }

}

