/**
 * SystemAPICatalogLinkSet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace Fusio.SDK;

public class SystemAPICatalogLinkSet
{
    [JsonPropertyName("anchor")]
    public string? Anchor { get; set; }

    [JsonPropertyName("service-desc")]
    public System.Collections.Generic.List<SystemAPICatalogLink>? ServiceDesc { get; set; }

    [JsonPropertyName("service-doc")]
    public System.Collections.Generic.List<SystemAPICatalogLink>? ServiceDoc { get; set; }

    [JsonPropertyName("service-meta")]
    public System.Collections.Generic.List<SystemAPICatalogLink>? ServiceMeta { get; set; }

    [JsonPropertyName("status")]
    public System.Collections.Generic.List<SystemAPICatalogLink>? Status { get; set; }

}

